name:                 maths-stuff
version:              0.1.0.0
visibility:           public
id:                   maths-stuff-0.1.0.0-inplace
key:                  maths-stuff-0.1.0.0-inplace
license:              MIT
maintainer:           oliviahrwalters@gmail.com
author:               Oliviax727
category:             Math
abi:                  inplace
exposed:              True
exposed-modules:      MyLib
hidden-modules:       BaseConverter
import-dirs:
    /home/ohrf/Desktop/Fun/maths-stuff/dist-newstyle/build/x86_64-linux/ghc-9.10.3/maths-stuff-0.1.0.0/build

library-dirs:
    /home/ohrf/Desktop/Fun/maths-stuff/dist-newstyle/build/x86_64-linux/ghc-9.10.3/maths-stuff-0.1.0.0/build

library-dirs-static:
    /home/ohrf/Desktop/Fun/maths-stuff/dist-newstyle/build/x86_64-linux/ghc-9.10.3/maths-stuff-0.1.0.0/build

dynamic-library-dirs:
    /home/ohrf/Desktop/Fun/maths-stuff/dist-newstyle/build/x86_64-linux/ghc-9.10.3/maths-stuff-0.1.0.0/build

data-dir:             /home/ohrf/Desktop/Fun/maths-stuff/.
hs-libraries:         HSmaths-stuff-0.1.0.0-inplace
depends:              base-4.20.2.0-f074
haddock-interfaces:
    /home/ohrf/Desktop/Fun/maths-stuff/dist-newstyle/build/x86_64-linux/ghc-9.10.3/maths-stuff-0.1.0.0/doc/html/maths-stuff/maths-stuff.haddock

haddock-html:
    /home/ohrf/Desktop/Fun/maths-stuff/dist-newstyle/build/x86_64-linux/ghc-9.10.3/maths-stuff-0.1.0.0/doc/html/maths-stuff
